/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class dokter extends javax.swing.JFrame {

    /**
     * Creates new form dokter
     */
    public dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jconadokt = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtdokter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 0, 180, 40);

        jLabel2.setText("pilih dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 40, 80, 30);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih salah satu --", "lee minho", "im yoona", "oh sehun", " " }));
        jconadokt.setName("lee minho\ndo kyungsoo\noh sehun"); // NOI18N
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(100, 40, 130, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setText("nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 50, 20);

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 50, 20);

        jLabel5.setText("usia");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 104, 40, 20);

        jLabel6.setText("jenis kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 150, 70, 20);

        jLabel7.setText("Golongan Darah");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 184, 80, 20);

        jLabel8.setText("Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 224, 60, 20);

        jLabel9.setText("Kewarganegaraan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 264, 90, 20);

        jLabel10.setText("Waktu Praktek");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 304, 80, 20);

        jLabel11.setText("Dokter spesialis");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 344, 90, 20);

        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(140, 20, 180, 30);
        jPanel1.add(jtxalamat);
        jtxalamat.setBounds(140, 60, 180, 30);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(140, 100, 180, 30);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(140, 140, 180, 30);
        jPanel1.add(jtxtgol);
        jtxtgol.setBounds(140, 180, 180, 30);
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(140, 220, 180, 30);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(140, 260, 180, 30);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(140, 300, 180, 30);
        jPanel1.add(jtxtdokter);
        jtxtdokter.setBounds(140, 340, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 110, 380, 380);

        setBounds(0, 0, 416, 543);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        // TODO add your handling code here:
        if (jconadokt.getSelectedItem().equals("lee minho")){
            jtxtnama.setText("Lee minho");
            jtxalamat.setText("jl.surabaya 16, malang");
            jtxtusia.setText("20 tahun");
            jtxtjenis.setText("Laki-laki");
            jtxtgol.setText("A");
            jtxtstatus.setText("belu menikah");
            jtxtkewar.setText("Indonesia");
            jtxtdokter.setText("Dokter umum");
            jtxtwaktu.setText("Pagi (07.00-15.00");
        }
        else
            if (jconadokt.getSelectedItem().equals("im yoona")){
            jtxtnama.setText("Dr.yoona");
            jtxalamat.setText("jl.danau towuti 4,malang");
            jtxtusia.setText("23 tahun");
            jtxtjenis.setText("perempuan");
            jtxtgol.setText("B");
            jtxtstatus.setText("menikah");
            jtxtkewar.setText("Indonesia");
            jtxtdokter.setText("Dokter gigi");
            jtxtwaktu.setText("Pagi (07.00-15.00");
    } else
        if (jconadokt.getSelectedItem().equals("oh sehun")){
        jtxtnama.setText("Dr.oh sehun");
        jtxalamat.setText("jl.danau towuti 4,malang");
        jtxtusia.setText("21 tahun");
        jtxtjenis.setText("LAKI_LAKI");
        jtxtgol.setText("AB");
        jtxtstatus.setText(" belum menikah");
        jtxtkewar.setText("korea kanada");
        jtxtdokter.setText("dokter bedah");
        jtxtwaktu.setText("Pagi (08.00-14.00");
    }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxalamat;
    private javax.swing.JTextField jtxtdokter;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
